Scenarios/ecommerce/src/Relecloud.Web/Models/Concert.cs
using System;
using System.Collections.Generic;

namespace Relecloud.Web.Models
{
    public class Concert
    {
        public int Id { get; set; }
        public string Artist { get; set; }
        public string Location { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public double Price { get; set; }
        public DateTimeOffset StartTime { get; set; }

        public IList<Review> Reviews { get; set; } = new List<Review>();
        public IList<Ticket> Tickets { get; set; } = new List<Ticket>();
    }
}

Scenarios/ecommerce/src/Relecloud.Web/Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Relecloud.Web.Infrastructure;
using Relecloud.Web.Models;
using Relecloud.Web.Services;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Relecloud.Web.Controllers
{
    public class CartController : Controller
    {
        #region Fields

        private readonly IConcertRepository concertRepository;
        private readonly IEventSenderService eventSenderService;

        #endregion

        #region Constructors

        public CartController(IConcertRepository concertRepository, IEventSenderService eventSenderService)
        {
            this.concertRepository = concertRepository;
            this.eventSenderService = eventSenderService;
        }

        #endregion

        #region Index

        public async Task<IActionResult> Index()
        {
            var model = await GetCartAsync();
            return View(model);
        }

        #endregion

        #region Add

        public async Task<IActionResult> Add(int concertId)
        {
            var model = await this.concertRepository.GetConcertByIdAsync(concertId);
            if (model == null)
            {
                return NotFound();
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult Add(int concertId, int count)
        {
            if (ModelState.IsValid)
            {
                var cartData = GetCartData();
                if (!cartData.ContainsKey(concertId))
                {
                    cartData.Add(concertId, 0);
                }
                cartData[concertId] = cartData[concertId] + count;
                SetCartData(cartData);
            }
            return RedirectToAction(nameof(Index));
        }

        #endregion

        #region Remove

        [HttpPost]
        public IActionResult Remove(int concertId)
        {
            if (ModelState.IsValid)
            {
                var cartData = GetCartData();
                if (cartData.ContainsKey(concertId))
                {
                    cartData.Remove(concertId);
                }
                SetCartData(cartData);
            }
            return RedirectToAction(nameof(Index));
        }

        #endregion

        #region Checkout

        [Authorize]
        public async Task<IActionResult> Checkout()
        {
            var model = await GetCartAsync();
            return View(model);
        }

        [Authorize]
        [HttpPost]
        [ActionName(nameof(Checkout))]
        public async Task<IActionResult> CheckoutConfirmed()
        {
            if (ModelState.IsValid)
            {
                // Create tickets for every item in the cart.
                var cartData = GetCartData();
                foreach (var concertId in cartData.Keys)
                {
                    for (var i = 0; i < cartData[concertId]; i++)
                    {
                        var ticket = new Ticket
                        {
                            ConcertId = concertId,
                            UserId = this.User.GetUniqueId()
                        };
                        await this.concertRepository.CreateTicketAsync(ticket);
                        await this.eventSenderService.SendEventAsync(Event.TicketCreated(ticket.Id));
                    }
                }
                
                // Remove all items from the cart.
                SetCartData(new Dictionary<int, int>());
            }
            return RedirectToAction(nameof(Index), "Ticket");
        }

        #endregion

        #region Helper Methods

        // The key is the concert ID, the value is the number of items in the cart.
        private IDictionary<int, int> GetCartData()
        {
            return this.HttpContext.Session.Get<IDictionary<int, int>>(nameof(Cart)) ?? new Dictionary<int, int>();
        }

        private void SetCartData(IDictionary<int, int> data)
        {
            // Remove keys that have don't have items in the cart anymore.
            foreach (var emptyItemKey in data.Where(item => item.Value <= 0).Select(item => item.Key).ToArray())
            {
                data.Remove(emptyItemKey);
            }
            this.HttpContext.Session.Set<IDictionary<int, int>>(nameof(Cart), data);
        }

        private async Task<Cart> GetCartAsync()
        {
            var cartData = GetCartData();
            var concertsInCart = await this.concertRepository.GetConcertsByIdAsync(cartData.Keys);
            var concertCartData = concertsInCart.ToDictionary(concert => concert, concert => cartData[concert.Id]);
            return new Cart(concertCartData);
        }

        #endregion
    }
}

Scenarios/ecommerce/src/Relecloud.Web/Controllers/ConcertController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Relecloud.Web.Infrastructure;
using Relecloud.Web.Models;
using Relecloud.Web.Services;
using System;
using System.Threading.Tasks;

namespace Relecloud.Web.Controllers
{
    public class ConcertController : Controller
    {
        #region Fields

        private readonly IConcertRepository concertRepository;
        private readonly IConcertSearchService concertSearchService;
        private readonly IEventSenderService eventSenderService;

        #endregion

        #region Constructors

        public ConcertController(IConcertRepository concertRepository, IConcertSearchService concertSearchService, IEventSenderService eventSenderService)
        {
            this.concertRepository = concertRepository;
            this.concertSearchService = concertSearchService;
            this.eventSenderService = eventSenderService;
        }

        #endregion

        #region Index

        public async Task<IActionResult> Index()
        {
            var model = await this.concertRepository.GetUpcomingConcertsAsync(10);
            return View(model);
        }

        #endregion

        #region Details

        public async Task<IActionResult> Details(int id)
        {
            var model = await this.concertRepository.GetConcertByIdAsync(id);
            if (model == null)
            {
                return NotFound();
            }
            return View(model);
        }

        #endregion

        #region Search

        public async Task<IActionResult> Search(string query)
        {
            var result = await this.concertSearchService.SearchAsync(query);
            return View(result);
        }

        #endregion

        #region Review

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Review(Review review)
        {
            if (ModelState.IsValid)
            {
                review.UserId = this.User.GetUniqueId();
                review.CreatedTime = DateTimeOffset.UtcNow;
                await this.concertRepository.AddReviewAsync(review);
                await this.eventSenderService.SendEventAsync(Event.ReviewCreated(review.Id));
            }
            return RedirectToAction(nameof(Details), new { id = review.ConcertId });
        }

        #endregion
    }
}

Scenarios/ecommerce/src/Relecloud.Web/Views/Concert/Details.cshtml
@model Relecloud.Web.Models.Concert
@{
    ViewData["Title"] = $"{Model.Artist} - {Model.Title}";
}
<h1>
    @Model.Artist &ndash; @Model.Title
    <span class="label label-info">@Model.Price.ToString("c")</span>
</h1>
<div class="text-muted">@Model.StartTime.UtcDateTime.ToString() &raquo; @Model.Location</div>
<div class="well offset-top-md">@Model.Description</div>
<a asp-controller="Cart" asp-action="Add" asp-route-concertId="@Model.Id" class="btn btn-success">Add To Cart &raquo;</a>

<fieldset>
    <legend>User Reviews</legend>
    @if (!Model.Reviews.Any())
    {
        <div class="alert alert-info">There aren't any reviews yet, be the first to add one below!</div>
    }
    @foreach (var review in Model.Reviews)
    {
        var ratingCssClass = review.Rating <= 1 ? "text-danger" : (review.Rating <= 2 ? "text-warning" : (review.Rating <= 3 ? "text-primary" : (review.Rating <= 4 ? "text-info" : "text-success")));
        <div class="media">
            <div class="media-left">
                <span class="glyphicon glyphicon-user" aria-hidden="true" style="width: 64px; height: 64px; font-size: 64px;"></span>
            </div>
            <div class="media-body">
                <h4 class="media-heading">
                    <span class="@ratingCssClass">
                        @for (var i = 0; i < review.Rating; i++)
                        {
                            <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                        }
                    </span>
                </h4>
                <div>@review.Description</div>
                @if (review.SentimentScore.HasValue)
                {
                    var sentimentCssClass = review.SentimentScore < 0.2f ? "text-danger" : (review.SentimentScore < 0.4f ? "text-warning" : (review.SentimentScore < 0.6f ? "text-primary" : (review.SentimentScore < 0.8f ? "text-info" : "text-success")));
                    var sentimentScoreInterpretation = review.SentimentScore < 0.2f ? "very negative" : (review.SentimentScore < 0.4f ? "fairly negative" : (review.SentimentScore < 0.6f ? "neutral" : (review.SentimentScore < 0.8f ? "fairly positive" : "very positive")));
                    <div class="small @sentimentCssClass">Sentiment Score: @review.SentimentScore.Value.ToString("0.000") (@sentimentScoreInterpretation)</div>
                }
                <div class="small text-muted">@review.CreatedTime.UtcDateTime.ToString()</div>
            </div>
        </div>
    }
</fieldset>

<fieldset>
    <legend>Your Review</legend>
    @if (!User.Identity.IsAuthenticated)
    {
        <div class="alert alert-warning">You have to <a asp-controller="Account" asp-action="SignIn" asp-route-returnurl="@this.Context.Request.Path">sign in</a> to add a review!</div>
    }
    else
    {
        <form asp-controller="Concert" asp-action="Review" method="post">
            <div>
                <input type="radio" name="rating" value="1" id="rating1" /> <label for="rating1" class="text-danger"><span class="glyphicon glyphicon-star" aria-hidden="true"></span> &mdash; Terrible</label><br />
                <input type="radio" name="rating" value="2" id="rating2" /> <label for="rating2" class="text-warning"><span class="glyphicon glyphicon-star" aria-hidden="true"></span><span class="glyphicon glyphicon-star" aria-hidden="true"></span> &mdash; Bad</label><br />
                <input type="radio" name="rating" value="3" id="rating3" /> <label for="rating3" class="text-primary"><span class="glyphicon glyphicon-star" aria-hidden="true"></span><span class="glyphicon glyphicon-star" aria-hidden="true"></span><span class="glyphicon glyphicon-star" aria-hidden="true"></span> &mdash; OK</label><br />
                <input type="radio" name="rating" value="4" id="rating4" /> <label for="rating4" class="text-info"><span class="glyphicon glyphicon-star" aria-hidden="true"></span><span class="glyphicon glyphicon-star" aria-hidden="true"></span><span class="glyphicon glyphicon-star" aria-hidden="true"></span><span class="glyphicon glyphicon-star" aria-hidden="true"></span> &mdash; Good</label><br />
                <input type="radio" name="rating" value="5" id="rating5" /> <label for="rating5" class="text-success"><span class="glyphicon glyphicon-star" aria-hidden="true"></span><span class="glyphicon glyphicon-star" aria-hidden="true"></span><span class="glyphicon glyphicon-star" aria-hidden="true"></span><span class="glyphicon glyphicon-star" aria-hidden="true"></span><span class="glyphicon glyphicon-star" aria-hidden="true"></span> &mdash; Excellent</label><br />
            </div>
            <div>
                <textarea name="description" class="form-control offset-top-md" placeholder="We appreciate your feedback!"></textarea>
            </div>
            <div>
                <input type="hidden" name="concertId" value="@Model.Id" />
                <input type="submit" class="btn btn-primary offset-top-md" value="Submit" />
            </div>
        </form>
    }
</fieldset>

Scenarios/ecommerce/src/Relecloud.Web/Views/Concert/Index.cshtml
@model IList<Relecloud.Web.Models.Concert>
@{
    ViewData["Title"] = "Upcoming Concerts";
}
<h1>@ViewData["Title"]</h1>
@if (!Model.Any())
{
    <div class="alert alert-info">There are no upcoming concerts.</div>
}
else
{
    <div class="list-group">
        @foreach (var concert in Model)
        {
            <div class="list-group-item">
                <h3 class="list-group-item-heading">
                    <a asp-controller="Concert" asp-action="Details" asp-route-id="@concert.Id">@concert.Artist &mdash; @concert.Title</a>
                    <span class="label label-info">@concert.Price.ToString("c")</span>
                </h3>
                <div class="text-muted">@concert.StartTime.UtcDateTime.ToString() &raquo; @concert.Location</div>
            </div>
        }
    </div>
}

Scenarios/ecommerce/src/Relecloud.Web/Views/Concert/Search.cshtml
@model IList<Relecloud.Web.Models.ConcertSearchResult>
@{
    ViewData["Title"] = "Search";
}
<h1>@ViewData["Title"]</h1>
@if (!Model.Any())
{
    <div class="alert alert-warning">Your query didn't return any results.</div>
}
else
{
    <div class="list-group">
        @foreach (var concert in Model)
        {
            <div class="list-group-item">
                <h3 class="list-group-item-heading">
                    <a asp-controller="Concert" asp-action="Details" asp-route-id="@concert.Id">@concert.Artist &mdash; @concert.Title</a>
                    <span class="label label-info">@concert.Price.ToString("c")</span>
                </h3>
                <div class="text-muted">@concert.StartTime.UtcDateTime.ToString() &raquo; @concert.Location</div>
                @if (concert.HitHighlights != null && concert.HitHighlights.Any())
                    {
                    <div class="alert alert-info offset-top-md">
                        @foreach (var hitHighlight in concert.HitHighlights)
                        {
                            <div class="highlight">@Html.Raw(hitHighlight)</div>
                        }
                    </div>
                }
            </div>
        }
    </div>
}